### ISSUE TITLE
Syntax error and possible logical bug

### ISSUE THREAD

**Issue by ZisisFl** [eellak/gsoc2019-anonymization#8]
https://github.com/eellak/gsoc2019-anonymization/blob/53324686d6194f0722f4b5a89c74991e881cbdc3/anonymizer/matcher_patterns.py#L403

In this line of code surnames_postfixes list has an syntax error, the last item of the list is a comma character. This error though doesn't show up when running the code which means either this part of code never gets reached either the init of a new list in the line 406 with exacly the same name as the one above outscopes surnames_postfixes. In any case the declaration of the first list has no effect on how the program works.

**Comment by dkatsiros** [comment]
Comma in the end of an array is valid in python. 
 You can read [this](https://stackoverflow.com/questions/11597901/why-are-trailing-commas-allowed-in-a-list).
Also you can check the example in [python documentation](https://docs.python.org/3.3/tutorial/datastructures.html#nested-list-comprehensions) in  `5.1.4. Nested List Comprehensions` .
